#!/bin/sh

docker rm bungee_config
docker rm lobby_config
docker rm creative_config
docker rm survival_config

if [ "$1" = "swarm" ]; then
	BUILD_ARGS='--build-arg="constraint:node==london"'
else
	BUILD_ARGS=''
fi

docker build -t bungee_config_img $BUILD_ARGS bungeecord
docker create \
	-e "constraint:node==london" \
	--name bungee_config \
	bungee_config_img /bin/true

docker build -t lobby_config_img $BUILD_ARGS lobby
docker create \
	-e "constraint:node==london" \
	--name lobby_config \
	lobby_config_img /bin/true

if [ "$1" = "swarm" ]; then
	BUILD_ARGS='--build-arg="constraint:node==amsterdam"'
else
	BUILD_ARGS=''
fi

docker build -t creative_config_img $BUILD_ARGS creative
docker create \
	-e "constraint:node==amsterdam" \
	--name creative_config \
	creative_config_img /bin/true

if [ "$1" = "swarm" ]; then
	BUILD_ARGS='--build-arg="constraint:node==frankfurt"'
else
	BUILD_ARGS=''
fi

docker build -t survival_config_img $BUILD_ARGS survival
docker create \
	-e "constraint:node==frankfurt" \
	--name survival_config \
	survival_config_img /bin/true

